# The following patch adds annotations to the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: connections.database.openshift.io
  annotations:
    service.binding/db.name: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.host: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.port: 'path={.status.dbConfigMap},objectType=ConfigMap'
    service.binding/db.user: 'path={.status.dbCredentials},objectType=Secret'
    service.binding/db.password: 'path={.status.dbCredentials},objectType=Secret'
